---

- name: Inclure la configuration Basic
  include_tasks: "../../../tasks/configure_basic.yml"

- name: Afficher l'utilisateur Ansible utilisé
  debug:
    msg: "L'utilisateur Ansible utilisé est {{ ansible_user }}"

- name: Test connection with ping
  ansible.windows.win_ping:

