---

- name: Afficher esxi_hostname
  debug:
    var: esxi_hostname

- name: Afficher la liste des hôtes dans windows_wds_rdp
  debug:
    var: groups['windows_wds_rdp']

- name: Configuration du CD-ROM sur les VMs cibles
  ansible.builtin.shell: |
    echo 'Arrêt de la VM avant ajout CDROM\n'
    govc vm.power -off -u 'https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_hostname }}' -k "{{ item }}"
    echo 'Ajout CD ROM\n'
    govc device.cdrom.add -u 'https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_hostname }}' -k -vm "{{ item }}"
    sleep 60
    govc device.connect -u 'https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_hostname }}' -k -vm "{{ item }}"
    echo 'Ajout de ISO windows 10\n'
    govc device.cdrom.insert -vm "{{ item }}" -u 'https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_hostname }}' -k '[datastore1] ISOs/Win10_20H2_French_x64.iso'
    echo 'Boot de la VM\n'
    govc vm.power -on -u 'https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_hostname }}' -k "{{ item }}"
    sleep 80
    echo "Fin du Script"
  loop: "{{ groups['windows_wds_rdp'] }}"
  when: groups['windows_wds_rdp'] | length > 0
