---

- name: Inclure la configuration Basic
  include_tasks: "../../../tasks/configure_basic.yml"

- name: Vérifier la configuration DNS de la carte réseau Ethernet1
  ansible.windows.win_shell: |
    (Get-DnsClientServerAddress -InterfaceAlias "Ethernet1").ServerAddresses -contains "172.16.2.61"
  register: dns_configured
  args:
    executable: powershell

- name: Configurer le DNS de la carte réseau Ethernet1
  ansible.windows.win_shell: |
    Set-DnsClientServerAddress -InterfaceAlias "Ethernet1" -ServerAddresses "172.16.2.61"
  args:
    executable: powershell
  when: not dns_configured.stdout
  changed_when: true  # Marque `changed` si la tâche s'exécute

- name: Joindre la machine au domaine Active Directory
  microsoft.ad.membership:
    state: domain
    dns_domain_name: "m2l.lan"
    domain_admin_user: "{{ ad_admin.username }}"
    domain_admin_password: "{{ ad_admin.password }}"
    domain_ou_path: "OU=Serveurs,OU=0_m2l.lan,DC=m2l,DC=lan"
    hostname: "M2L-WSRV02"
    reboot: yes
 # when: not domain_membership.stdout
 # changed_when: true  # Marque `changed` si la tâche s'exécute

- name: Créer le dossier temporaire C:\Temp si nécessaire
  ansible.windows.win_file:
    path: "C:\\Temp"
    state: directory

- name: Copier le script ConfigureRemotingForAnsible.ps1 sur la machine cible
  win_copy:
    src: ../files/ConfigureRemotingForAnsible.ps1
    dest: "C:\\Temp\\ConfigureRemotingForAnsible.ps1"
  register: copy_result
  changed_when: copy_result.changed  # Change uniquement si le fichier est copié

- name: Exécuter le script ConfigureRemotingForAnsible.ps1
  win_shell: |
    Set-ExecutionPolicy RemoteSigned -Force
    C:\Temp\ConfigureRemotingForAnsible.ps1
  args:
    executable: powershell



- name: Activer CredSSP sur le serveur et le client
  ansible.windows.win_shell: |
    Enable-WSManCredSSP -Role Server -Force
    Enable-WSManCredSSP -Role Client -DelegateComputer 192.168.62.52 -Force
  args:
    executable: powershell
  changed_when: false  # Marque `changed` si la tâche s'exécute

- name: Inclure la configuration ad credssp
  include_tasks: "../../../tasks/configure_ad_credssp.yml"


- name: Tester la connexion avec un ping
  ansible.windows.win_ping:
