---

# 1. Installer wget et gnupg
- name: Installer wget et gnupg pour la gestion du dépôt Centreon
  ansible.builtin.apt:
    name:
      - wget
      - gnupg
    state: present
    update_cache: yes

# 2. Ajouter la clé GPG et les dépôts Centreon
- name: Ajouter le dépôt apt-standard de Centreon
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/centreon.list
    content: "deb https://packages.centreon.com/apt-standard-24.10-stable/ {{ centreon_codename }} main\n"
    mode: '0644'

- name: Ajouter le dépôt apt-plugins de Centreon
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/centreon-plugins.list
    content: "deb https://packages.centreon.com/apt-plugins-stable/ {{ centreon_codename }} main\n"
    mode: '0644'

- name: Télécharger et ajouter la clé GPG de Centreon
  ansible.builtin.shell: |
    wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null
  args:
    creates: /etc/apt/trusted.gpg.d/centreon.gpg


# 3. Mise à jour des paquets
- name: Mettre à jour les paquets
  ansible.builtin.apt:
    update_cache: yes

# 4. Installer Centreon
- name: Installer Centreon
  ansible.builtin.apt:
    name: "{{ centreon_deps }}"
    state: present

# 5. Création des bases de données Centreon
- name: Créer les bases de données Centreon
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - "{{ centreon_db_name }}"
    - centreon_storage
    - centreon_storage_data_bin

- name: Créer l'utilisateur MySQL pour Centreon avec les privilèges sur toutes les bases
  mysql_user:
    name: "{{ centreon_db_user }}"
    password: "{{ centreon_db_password }}"
    priv: >
      {{ centreon_db_name }}.*:ALL,
      centreon_storage.*:ALL,
      centreon_storage_data_bin.*:ALL
    host: "localhost"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

