---

- name: Vérifier si la base de données GLPI existe déjà
  mysql_db:
    name: glpi
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  register: glpi_db_check

- name: Créer un utilisateur MySQL/MariaDB pour GLPI
  mysql_user:
    name: glpi
    password: "Btssio75000"
    priv: "glpi.*:ALL"
    host: "localhost"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  when: glpi_db_check is changed

- name: Installation automatique de GLPI avec les paramètres définis
  command: >
    php bin/console -n db:install
    -H {{ glpi_db_host }}
    -P 3306
    -L fr_FR
    -d {{ glpi_db_name }}
    -u {{ glpi_db_user }}
    -p {{ glpi_db_password }}
    --reconfigure --force
  args:
    chdir: "/var/www/glpi"
  become: yes
  register: glpi_install_result
  changed_when: "'GLPI successfully installed' in glpi_install_result.stdout"

- name: Vérification et correction des permissions du fichier php-errors.log
  file:
    path: /var/www/glpi/files/_log/php-errors.log
    state: touch
    owner: www-data
    group: www-data
    mode: '664'

- name: Supprimer les sessions et le cache de GLPI après installation
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/www/glpi/files/_sessions/*
    - /var/www/glpi/files/_cache/*

- name: Modifier les mots de passe des comptes GLPI par défaut via SQL
  mysql_query:
    login_host: "{{ glpi_db_host }}"
    login_user: "{{ glpi_db_user }}"
    login_password: "{{ glpi_db_password }}"
    login_db: "{{ glpi_db_name }}"
    query: >
      UPDATE glpi_users
      SET password = MD5('{{ item.password }}')
      WHERE name = '{{ item.username }}';
  loop:
    - { username: "glpi", password: "{{ glpi_admin_password }}" }
    - { username: "tech", password: "{{ glpi_tech_password }}" }
    - { username: "normal", password: "{{ glpi_normal_password }}" }
    - { username: "post-only", password: "{{ glpi_postonly_password }}" }
  become: yes


- name: Supprimer le fichier install.php après installation
  file:
    path: /var/www/glpi/install/install.php
    state: absent
