- name: Configurer un utilisateur AD avec Basic
  set_fact:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_user: "{{ ad_basic_user.username }}"
    ansible_password: "{{ ad_basic_user.password }}"
    ansible_winrm_server_cert_validation: ignore


