---
- name: Démarrer chaque VM sur ESXi du groupe {{ target_group }}
  vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    validate_certs: no
    name: "{{ hostvars[item].inventory_hostname }}"
    state: poweredon
  delegate_to: localhost
  loop: "{{ groups[target_group] }}"
  loop_control:
    label: "{{ hostvars[item].inventory_hostname }}"

- name: Attendre que chaque VM soit accessible en SSH/winRM
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ hostvars[item].wait_for_port }}"
    delay: 10
    timeout: 300
  delegate_to: localhost
  loop: "{{ groups[target_group] }}"
  loop_control:
    label: "{{ hostvars[item].inventory_hostname }}"
