---
# tasks file for install_dns

- name: Inclure la configuration ad credssp
  include_tasks: "../../../tasks/configure_basic.yml"

- name: Installer le rôle DNS
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: yes
  register: dns_role_installation

- name: Configurer le DNS de la carte réseau Ethernet1
  ansible.windows.win_shell: |
    $AdapterName = "Ethernet1"
    $DnsServer = "127.0.0.1"
    Get-NetAdapter -Name $AdapterName | Set-DnsClientServerAddress -ServerAddresses $DnsServer
  args:
    executable: powershell
  when: dns_role_installation.changed

- name: Créer une zone de recherche directe (ZRD)
  ansible.windows.win_dns_zone:
    name: "{{ dns_zrd_name }}"
    type: Primary
    Replication: none
    state: present
  register: create_zone_result

#- name: Importer le module DnsServer
#  ansible.windows.win_shell: |
#    Import-Module DnsServer

- name: Configurer les mises à jour dynamiques sur la zone ZRD
  ansible.windows.win_shell: |
    Set-DnsServerPrimaryZone -Name "{{ dns_zrd_name }}" -DynamicUpdate "NonsecureAndSecure"
  when: create_zone_result.changed  # N'exécuter que si la zone a été créée
  register: dynamic_update_result

- name: Créer une zone de recherche indirecte (ZRI)
  ansible.windows.win_dns_zone:
    name: "{{ dns_zri_name }}"
    type: Primary
    Replication: none
    state: present
  register: create_zone_result

- name: Configurer les mises à jour dynamiques sur la zone ZRD
  ansible.windows.win_shell: |
    Set-DnsServerPrimaryZone -Name "{{ dns_zri_name }}" -DynamicUpdate "NonsecureAndSecure"
  when: create_zone_result.changed  # N'exécuter que si la zone a été créée
  register: dynamic_update_result

- name: Vérifier si le redirecteur existe
  ansible.windows.win_shell: |
    $Redirector = "8.8.8.8"
    (Get-DnsServerForwarder | Where-Object { $_.IPAddress -eq $Redirector }) | Out-Null
    if ($?) { Write-Output $true } else { Write-Output $false }
  args:
    executable: powershell
  register: dns_forwarder_exists

- name: Ajouter le redirecteur si absent
  ansible.windows.win_shell: |
    Add-DnsServerForwarder -IPAddress "8.8.8.8" -PassThru
  args:
    executable: powershell
  when: not dns_forwarder_exists.stdout | bool


- name: Ajouter des enregistrements A
  ansible.windows.win_dns_record:
    name: "{{ item.name }}"
    zone: "{{ dns_zrd_name }}"
    type: A
    ttl: 3600
    value: "{{ item.address }}"
  loop: "{{ dns_a_records }}"

- name: Ajouter des enregistrements CNAME
  ansible.windows.win_dns_record:
    name: "{{ item.alias }}"
    zone: "{{ dns_zrd_name }}"
    type: CNAME
    ttl: 3600
    value: "{{ item.target }}"
  loop: "{{ dns_cname_records }}"



