---
- name: Démarrer la VM via ESXi et attendre son accessibilité
  hosts: localhost
  gather_facts: no
  vars:
    target_group: "debian_squid"
  tasks:
    - name: Inclure la tâche de démarrage des VMs
      include_tasks: "../tasks/vm_esxi_start.yml"

#- name: Mettre à jour l'IP de la seconde carte réseau dans la VM
#  hosts: "debian_squid"  # ou un hôte spécifique
#  gather_facts: yes
#  become: yes
#  tasks:
#    - name: Mettre à jour l'IP de la seconde interface
#      include_tasks: "../tasks/vm_update_second_ip.yml"

- name: Installer Squid sur la VM démarrée
  hosts: "debian_squid"
  gather_facts: yes
  become: yes
  roles:
    - vm_update_2nd_interface
    - install_squid

- name: Supprimer les accès externes 
  hosts: "debian_squid"
  gather_facts: yes
  become: yes
  roles:
    - vm_remove_first_ip
