---
#
- name: Test win_ping on windows
  hosts: M2L-WSRV01
  become: false
  gather_facts: false
#  vars:
#    ns_a_records:
#      - { name: "www", address: "192.168.1.10" }
#      - { name: "mail", address: "192.168.1.20" }
#    dns_cname_records:
#      - { alias: "ftp", target: "www.example.com" }
#      - { alias: "api", target: "www.example.com" }
  #
  roles:
    - install_dns
