---
#

- name: Configure CD/DVD on ESXi
  hosts: localhost
  roles:
    - configure_cdrom

- name: Installe WDS sur un serveur windows 2019
  hosts: windows_wds_rdp
  become: false
  gather_facts: false
  #
  roles:
#    - win_ping
    - integrerAD
    - install_wds
