---

- name: Démarrer la VM via ESXi et attendre son accessibilité
  hosts: localhost
  gather_facts: no
  vars:
    target_group: "windows_dns_dhcp_ad"
  tasks:
    - name: Inclure la tâche de démarrage des VMs
      include_tasks: "../tasks/vm_esxi_start.yml"

- name: Installer Squid sur la VM démarrée
  hosts: windows_dns_dhcp_ad
  gather_facts: no
  roles:
    - vm_update_2nd_interface
